[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
reqwest = { version = "0.12.3", features = ["json"] }
tokio = { version = "1.4.0", features = ["full"] }
serde_json = "1.0.68"
