[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
reqwest = { version = "0.12.3", features = ["json"] }
tokio = { version = "1.4.0", features = ["full"] }
tokio-tungstenite = "0.21.0"
futures-util = "0.3.30"
serde_json = "1.0.115"
